*** Inbox.org
:PROPERTIES:
:VISIBILITY: children
:END:

**** Treefactor | FR - enhancement | cascade by default
:PROPERTIES:
:ID:       4E43FDC0-B2EF-42A2-AC9D-40ED1382EDF6
:END:

I'm concerned that the skill floor for FIIR - Fast Iterative Inductive Refiling - is too high. Making cascade the default would reduce ambiguity and therefore difficulty. It's impractical to adopt without an ergonomic means of renumbering Dired directories. Org already has this via org-move-item-up on a numbered list, so the code could be adapted. This should be part of Treefactor.

Once the code is added to Treefactor, I'll need to refactor Littlebook's Textmind going forward to conform to the new convention.

**** TODO fix treefactor up func

throw-up is definitely broken when throwing from inside a 0-inbox
need to fix that
maybe it triggers false failure only when there's already a 0-inbox dir created at the destination, but not the identical filename within it.
[2020-04-30 Thu 22:54]

**** treefactor | functions | interactive | namespace | collisions | "heading" | don't fix

***** collisions

Should I rename treefactor-org-refactor-heading and treefactor-org-duplicate-heading-to-other-window
so that leo-headingfy won't get collisions in M-x?
  [2019-12-26 Thu 21:53]

***** status quo | benefits

descriptive function names are good. and it would be extra work.

***** helm machine learning fixes collisions

does helm learn what I want? try restarting to see.
[2020-01-03 Fri 22:09]

restarted emacs.
yes, it appears helm does learn. headingfy ranked first for M-x head

***** no change needed

good enough.
[2020-01-03 Fri 22:10]

canceling task.

even if there's some initial friction from M-x errors, headingfy is much less cognitively intense than refactor, and thus the friction isn't important enough to justify the required effort and resulting confusion.
[2020-01-03 Fri 22:11]

**** Treefactor | critical bugfix

You're right, and this is a data-loss bug! I guess I'm going to have to write some tests to prevent this from happening again. Thank you for catching this. I don't know how much data I've lost this way. My inexperience is really showing here. I'll fix it ASAP.
[2020-05-16 Sat 23:30]

Ok, I've reliably reproduced the bug. This only affects a particular use of treefactor-up that is a very rare part of my workflow:

in directory ~/foobar
create file ~/foobar/baz
add headings to it
run treefactor-up on all the headings
the first heading will correctly appear in ~/foobar/Inbox.org
  UNLESS Inbox.org already exists. then the heading will disappear silently
all subsequent headings will disappear silently.
[2020-05-16 Sat 23:47]

This bug also affects treefactor-refile a heading to a filename (not a directory) in Dired. Really bad. Also a rare part of my workflow.
[2020-05-17 Sun 00:05]

This bug also affects treefactor-refile a heading to a filename (not a directory) in Dired. Really bad. Also a rare part of my workflow.

The culprit is treefactor-insert-text-to-file-blind, which was missing a progn. Fix should be out soon.

whew, released the fix
man, that was stupid.
gotta write tests!
[2020-05-17 Sun 00:34]

**** treefactor needs a function that can reorder pretty path "directories" while pipified

**** treefactor | FR | pipify | extension

nice, M-t transpose works around pipes
don't need to write the function after all
[2020-06-08 Mon 00:34]

eh it still helps a lot for multi-word titles though
would be nice to have a function that decomposes pipes into lines as well

**** Treefactor | bug | treefactor-up | within 0-Inbox | intermittent

H-g runs the command leo-up
fails when run on a file from within a 0-Inbox
important bug to fix
[2020-06-16 Tue 01:14]

**** TODO add [[id:0117A4A0-6C64-43A1-BC81-5B31DF37601B][A GitHub Action for Emacs Lisp CI]] to Treefactor

**** Selectrum better than Avy for Treefactor?

https://github.com/raxod502/selectrum
might be a better way to pick Treefactor targets than Avy!
[2020-12-08 Tue 20:15]

**** treefactor bugged outside Spacemacs

#+begin_quote
WhangdoodleToday at 3:54 AM
Have you tested treefactor sans Spacemacs?
 
WhangdoodleToday at 4:47 AM
Attempting set up sans Spacemacs.
 Working my way through treefactor commands.
treefactor-throw doesn't make an Inbox.org if the directory in the next window doesn't already have one.
[4:47 AM]
treefactor-up does work, kind of. Succesfully moves a heading to Inbox.org, creating if needed, but
[4:49 AM]
1. Messages shows treefactor-insert-text-to-file-blind: Symbol's value as variable is void: user-home-directory
(Not a default variable in vanilla emacs, but it exists in spacemacs.)
[4:50 AM]
2. treefactor-up leaves source org file narrowed to headline--which has been moved to Inbox.org. Gives the appearance of an empty buffer or file.
[4:52 AM]
3. treefactor-up switched the source window to the Inbox.org buffer even when that buffer appeared in another window of the same frame. This surprise meant it took a while to return to the original source buffer. 
Inconvenient for day log processing
 
WhangdoodleToday at 5:06 AM
However, treefactor-throw seems to work AFTER copying
(defconst user-home-directory (expand-file-name "~/") "User home directory (~/).") from spacemacs's .emacs.d/core/core-load-paths.el to emacs's scratch buffer and evaluating it there.
[5:09 AM]
As an aside, is the workflow to have two windows in one frame, one with the source and the other with the target?
#+end_quote

Very little testing outside Spacemacs.  Those sound like critical bugs.  I'll prioritize fixing them.
really need to write a test suite.  maybe this would be the time, to avoid introducing further bugs.
[2021-01-19 Tue 05:17]

**** treefactor bug cont

#+begin_quote
prefcToday at 11:25 AM

I had the same issues (although at the time I only identified issue #1), but I thought it was because of some specific configuration in Doom Emacs.  I think I tried it in vanilla Emacs, it worked then.  One of the early versions before the name changed.
#+end_quote
[2021-01-19 Tue 15:59]

**** treefactor bug report

#+begin_quote
prefcToday at 7:13 PM

This fixes it for me:
(defun treefactor-text-inserted-to-buffer-path-message ()
  "Report filename that text was inserted to.

Reported path is relative to vd-root-dir or ~/."

  (message "Inserted text into `%s'" ;; (if (vc-root-dir)
                                         (expand-file-name buffer-file-name (vc-root-dir))
                                       ;; (expand-file-name buffer-file-name user-home-directory))
                                       ))

Or one could just remove the %s until it's fixed upstream.
[7:15 PM]
removing user-home-directory in treefactor-org-dired-zinks fixes it.(edited)
[7:20 PM]
Not completely sure about Zinks.
#+end_quote
[2021-01-19 Tue 19:30]

**** dev handbook | alphapapa@ | container & testing | useful for Treefactor

https://alphapapa.github.io/emacs-package-dev-handbook/#outline-container-Testing

This is great, and the libraries sound especially good for treefactor.

Assess library probably has some code best practices Treefactor could adopt, as well.

multiple of the libraries are useful.  cool.
[2021-01-21 Thu 09:05]

**** treefactor | testing setup | start by making a cask file

cask manual
https://cask.readthedocs.io/en/latest/index.html

so, where to begin?
Well, every Emacs package should have a cask file.
I can agree to that principle.
So that's an easy place to start.
[2021-01-21 Thu 08:45]

**** treefactor | testing | verification and validation | non-code questions

https://en.wikipedia.org/wiki/Software_verification_and_validation

verification and validation are soft concepts which don't require code for this stage.
[2021-01-21 Thu 07:38]

**** Treefactor | testing | tools to use | ecukes and buttercup

https://en.wikipedia.org/wiki/Integration_testing

sounds like I need both unit testing and integration testing
integration is probably more important, given I care about results
and that requires the interoperation of dired and org with treefactor.

so I'm using ecukes certainly, and probably also buttercup
[2021-01-21 Thu 07:35]
