* Treesort

** Introduction

Treesort replicates the "Throw" functionality of the Windows
application "BrainStorm".

BrainStorm is an outliner that allows rapid text sorting into nested
hierarchical layers. It is hosted at
http://www.brainstormsw.com

Org-Mode already has outliner functionality.  It refiles headings
well.  However, I have not found anything in Org-Mode or Emacs that
matches BrainStorm's ability to rapidly "throw" individual lines to
the appropriate subheadings of an outline.

Refiling headings is not an adequate substitute for refiling lines.
Transforming every single line into a heading generates a huge mess.
This task should be easy, fast and fun, not painful.

Thanks to the power of Elisp, Treesort actually improves on the
BrainStorm's strongest capabilities.

** Instructions

First, you should bind ts-throw to your preferred keychord.  It is
the only command you will need to s(n)ort lines.

Next, you should understand how ts-throw works.  Here's the
human-friendly version:

ts-throw will kill the whole line at point.  It will ask you for the
first letter(s) of your target child heading.  Then it will append
the line to that heading as an invisible background operation.

*** The long version

Here is a more technical explanation, so that you can avoid
surprises:

1. ts-throw believes that the "parent" outline heading is at the top
of the visible buffer.  You should narrow the region to your desired
parent heading before using ts-throw.

2. ts-throw will only throw to an immediate child of the parent
heading.  This prevents you from unknowingly sending a line to a
buried heading with a similar prefix.

3. You can still throw an "interception" if you use a prefix that is
shared by another immediate child heading that is positioned before
your intended target.  So be wary of single-letter prefixes, and be
careful when throwing to a crowd of potential targets.  (The Windows
BrainStorm application only allowed 6 simultaneous targets.
Sometimes the brain works faster when it has fewer options to
juggle.  However, ts-throw sets no limit on the number of targets.)

4. If ts-throw cannot find a child heading that matches your prefix,
it will echo a "Search failed:" error in the minibuffer.  Your line
will not be killed.

5. You can grab lines from any level of the outline.

6. ts-throw will not disturb your view.  Exception - if you throw to
a collapsed heading, the thrown line will not be hidden until you
refresh the visibility for that heading.  If this becomes bothersome
due to large number of lines, use C-c C-k
org-kill-note-or-show-branches to re-hide everything.

For further information, see the extensively commented source code.
This is my first program!

** Roadmap and Tips

Org-Mode's default settings offer reasonably good outline visibility
controls, but the defaults are not perfect.

For example, the widen + outline-up-heading + org-narrow-to-subtree
process is painfully cumbersome.  This can be corrected by recording
and keybinding a simple keyboard macro.

Also, the oddly-named obscure C-c C-k org-kill-note-or-show-branches
is a great way to clean up the outline view during sorting.

