*** Inbox.org
:PROPERTIES:
:VISIBILITY: children
:END:

**** Treefactor | replace cl-assert with should

> should is a macro with the same meaning as cl-assert but better error reporting

I should replace any asserts in Treefactor with should.
[2021-01-29 Fri 09:58]

**** emacs manual  | cl section | review compliance with treefactor

I should read through
https://www.gnu.org/software/emacs/manual/html_node/cl/index.html#Top
with regard to Treefactor and ensure compliance and full utilization
[2021-01-29 Fri 10:08]

**** I should add an error for when treefactor expects text entered into the isearch form but there's none.

I should add an error for when treefactor expects text entered into the isearch form but there's none.
eh guess I can't though, because isearch handover
but maybe after handback I can?  with isearch last-string variable
[2021-02-08 Mon 16:50]

**** ace-isearch | A seamless bridge between isearch, ace-jump-mode, avy, and helm-swoop. | for Treefactor?

https://github.com/tam17aki/ace-isearch
A seamless bridge between isearch, ace-jump-mode, avy, and helm-swoop.

MIght help with Treefactor.
[2021-02-09 Tue 09:34]

**** ElispCookbook | Compare with Treefactor.

https://www.emacswiki.org/emacs/ElispCookbook
Compare with Treefactor.
[2021-02-09 Tue 09:35]

**** failure tolerance | engineering principle | apply to Treefactor

> the fundamental idea with airplane design is not to design components that cannot fail, as that is impossible. The idea is to design the system to be tolerant of failure. Every part in the system is not "how can we make this part never fail" but "assume it failed. How does the airplane survive?"
This is a fundamental shift in viewpoint.
