*** Inbox.org
:PROPERTIES:
:VISIBILITY: children
:END:

**** treefactor bugged outside Spacemacs

#+begin_quote
WhangdoodleToday at 3:54 AM
Have you tested treefactor sans Spacemacs?
 
WhangdoodleToday at 4:47 AM
Attempting set up sans Spacemacs.
 Working my way through treefactor commands.
treefactor-throw doesn't make an Inbox.org if the directory in the next window doesn't already have one.
[4:47 AM]
treefactor-up does work, kind of. Succesfully moves a heading to Inbox.org, creating if needed, but
[4:49 AM]
1. Messages shows treefactor-insert-text-to-file-blind: Symbol's value as variable is void: user-home-directory
(Not a default variable in vanilla emacs, but it exists in spacemacs.)
[4:50 AM]
2. treefactor-up leaves source org file narrowed to headline--which has been moved to Inbox.org. Gives the appearance of an empty buffer or file.
[4:52 AM]
3. treefactor-up switched the source window to the Inbox.org buffer even when that buffer appeared in another window of the same frame. This surprise meant it took a while to return to the original source buffer. 
Inconvenient for day log processing
 
WhangdoodleToday at 5:06 AM
However, treefactor-throw seems to work AFTER copying
(defconst user-home-directory (expand-file-name "~/") "User home directory (~/).") from spacemacs's .emacs.d/core/core-load-paths.el to emacs's scratch buffer and evaluating it there.
[5:09 AM]
As an aside, is the workflow to have two windows in one frame, one with the source and the other with the target?
#+end_quote

Very little testing outside Spacemacs.  Those sound like critical bugs.  I'll prioritize fixing them.
really need to write a test suite.  maybe this would be the time, to avoid introducing further bugs.
[2021-01-19 Tue 05:17]

#+begin_quote
prefcToday at 11:25 AM

I had the same issues (although at the time I only identified issue #1), but I thought it was because of some specific configuration in Doom Emacs.  I think I tried it in vanilla Emacs, it worked then.  One of the early versions before the name changed.
#+end_quote
[2021-01-19 Tue 15:59]

#+begin_quote
prefcToday at 7:13 PM

This fixes it for me:
(defun treefactor-text-inserted-to-buffer-path-message ()
  "Report filename that text was inserted to.

Reported path is relative to vd-root-dir or ~/."

  (message "Inserted text into `%s'" ;; (if (vc-root-dir)
                                         (expand-file-name buffer-file-name (vc-root-dir))
                                       ;; (expand-file-name buffer-file-name user-home-directory))
                                       ))

Or one could just remove the %s until it's fixed upstream.
[7:15 PM]
removing user-home-directory in treefactor-org-dired-zinks fixes it.(edited)
[7:20 PM]
Not completely sure about Zinks.
#+end_quote
[2021-01-19 Tue 19:30]
